[package]
name = "sprocket"
version = "0.1.0"
authors = ["Asher Baker <asherkin@limetech.io>"]
edition = "2018"
description = "Modern sockets for SourceMod"

[lib]
crate-type = ["cdylib"]

[dependencies]
sm-ext = { git = "https://github.com/asherkin/sm-ext-rs" }
futures = "0.3"
async-std = "1.4"
